name: Cloud Function Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: 
      - master
      - staging
    paths:
      - functions/**/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  deploy-functions:
    # runner
    runs-on: ubuntu-latest
    
    # docker images
    container: node:lts
    
    # script
    steps:
      - name: Navigate to functions folder
        run: cd functions
        
      - name: Install dependencies
        run: npm install
        
      - name: Redirect back from functions folder
        run: cd ..
        
      - name: Deploy firebase functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
