name: Cloud Function Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: 
      - master
      - staging
    paths:
      - functions/**/*
      
  pull_request:
    branches:
      - master
      - staging
    paths:
      - functions/**/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
  deploy-functions:
    # runner
    runs-on: ubuntu-latest
    
    # docker images
    container: node:lts
    
    # script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install firebase-tools
        run: npm i -g firebase-tools
        
      - name: Install dependencies
        run: npm install
        working-directory: functions
        
      - name: Deploy firebase functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: functions
